from io import BytesIO
import re

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import (
    getSampleStyleSheet,
    ParagraphStyle
)
from reportlab.lib.units import mm

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image,
    PageBreak
)

LOGO_PATH = "assets/tenderlens_logo.png"
WATERMARK_PATH = "assets/TL_logo.png"


# =====================================================
# HELPERS
# =====================================================

def clean_description(text):

    if text is None:
        return ""

    text = str(text)

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    text = re.sub(
        r",(?=\S)",
        ", ",
        text
    )

    text = re.sub(
        r"\.(?=[A-Za-z])",
        ". ",
        text
    )

    return text.strip()


# =====================================================
# WATERMARK
# =====================================================

def add_page_elements(canvas, doc):

    canvas.saveState()

    try:

        canvas.setFillAlpha(0.08)

        canvas.drawImage(
            WATERMARK_PATH,
            45 * mm,
            70 * mm,
            width=120 * mm,
            height=110 * mm,
            preserveAspectRatio=True,
            mask="auto"
        )

    except:
        pass

    canvas.setFillAlpha(1)

    canvas.setFont(
        "Helvetica",
        8
    )

    canvas.drawRightString(
        195 * mm,
        8 * mm,
        f"Page {canvas.getPageNumber()}"
    )
    
    canvas.drawCentredString(
    	105 * mm,
	8 * mm,
	"www.tenderlens.in"
    )

    canvas.drawString(
        15 * mm,
        8 * mm,
        "Generated by TenderLens"
    )

    canvas.restoreState()


# =====================================================
# PDF
# =====================================================

def create_tender_pdf(
    tender,
    boq_df
):

    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=12 * mm,
        rightMargin=12 * mm,
        topMargin=12 * mm,
        bottomMargin=15 * mm
    )

    styles = getSampleStyleSheet()

    body_style = ParagraphStyle(
        "Body",
        parent=styles["BodyText"],
        leading=14
    )

    boq_style = ParagraphStyle(
        "BOQ",
        parent=styles["BodyText"],
        leading=12
    )

    story = []

    # =================================================
    # LOGO
    # =================================================

    try:

        story.append(

            Image(
                LOGO_PATH,
                width=75 * mm,
                height=30 * mm
            )

        )

    except:
        pass

    story.append(
        Spacer(
            1,
            6
        )
    )

    story.append(
        Paragraph(
            "<b>TENDER DETAILS</b>",
            styles["Title"]
        )
    )

    story.append(
        Spacer(
            1,
            6
        )
    )

    # =================================================
    # SUMMARY
    # =================================================

    org_chain = str(

        tender.get(
            "organisation_chain_raw",
            ""
        )

    ).replace(
        "||",
        "<br/>"
    )

    summary_data = [

        [
            Paragraph(
                "<b>Tender ID</b>",
                body_style
            ),
            Paragraph(
                str(
                    tender.get(
                        "tender_id",
                        ""
                    )
                ),
                body_style
            )
        ],

        [
            Paragraph(
                "<b>Name of Work</b>",
                body_style
            ),
            Paragraph(
                str(
                    tender.get(
                        "title",
                        ""
                    )
                ),
                body_style
            )
        ],

        [
            Paragraph(
                "<b>Organisation</b>",
                body_style
            ),
            Paragraph(
                org_chain,
                body_style
            )
        ],

        [
            Paragraph(
                "<b>Location</b>",
                body_style
            ),
            Paragraph(
                str(
                    tender.get(
                        "location",
                        ""
                    )
                ),
                body_style
            )
        ],

        [
            Paragraph(
                "<b>Tender Value</b>",
                body_style
            ),
            Paragraph(
                str(
                    tender.get(
                        "tender_value",
                        ""
                    )
                ),
                body_style
            )
        ],

        [
            Paragraph(
                "<b>Closing Date</b>",
                body_style
            ),
            Paragraph(
                str(
                    tender.get(
                        "bid_submission_end_date",
                        ""
                    )
                ),
                body_style
            )
        ],

        [
            Paragraph(
                "<b>Authority</b>",
                body_style
            ),
            Paragraph(
                str(
                    tender.get(
                        "tender_inviting_authority",
                        ""
                    )
                ),
                body_style
            )
        ],

        [
            Paragraph(
                "<b>Authority Address</b>",
                body_style
            ),
            Paragraph(
                str(
                    tender.get(
                        "authority_address",
                        ""
                    )
                ),
                body_style
            )
        ]

    ]

    summary_table = Table(
        summary_data,
        colWidths=[
            42 * mm,
            130 * mm
        ]
    )

    summary_table.setStyle(

        TableStyle([

            (
                "GRID",
                (0, 0),
                (-1, -1),
                0.5,
                colors.black
            ),

            (
                "BACKGROUND",
                (0, 0),
                (0, -1),
                colors.HexColor("#E9ECEF")
            ),

            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "TOP"
            )

        ])

    )

    story.append(
        summary_table
    )

    story.append(
        Spacer(
            1,
            10
        )
    )

    # =================================================
    # WORK DESCRIPTION
    # =================================================

    story.append(

        Paragraph(
            "<b>Work Description</b>",
            styles["Heading2"]
        )

    )

    story.append(

        Paragraph(
            str(
                tender.get(
                    "work_description",
                    ""
                )
            ),
            body_style
        )

    )

    story.append(
        Spacer(
            1,
            10
        )
    )

    # =================================================
    # BOQ
    # =================================================

    story.append(

        Paragraph(
            "<b>BOQ Items</b>",
            styles["Heading2"]
        )

    )

    boq_data = [[

        Paragraph("<b>Item No</b>", body_style),

        Paragraph("<b>Description</b>", body_style),

        Paragraph("<b>Qty</b>", body_style),

        Paragraph("<b>Unit</b>", body_style)

    ]]

    for _, row in boq_df.iterrows():

        desc = clean_description(
            row["description"]
        )

        parts = desc.split(
            ":",
            1
        )

        if len(parts) == 2:

            code = parts[0].strip()

            description = parts[1].strip()

            desc_html = (

                f"<b>{code}</b><br/>"
                f"{description}"

            )

        else:

            desc_html = desc

        unit = str(
            row["unit"]
        )

        unit = unit.replace(
            " per ",
            "<br/>per "
        )

        boq_data.append([

            Paragraph(
                str(
                    row["item_no"]
                ),
                boq_style
            ),

            Paragraph(
                desc_html,
                boq_style
            ),

            Paragraph(
                str(
                    row["quantity"]
                ),
                boq_style
            ),

            Paragraph(
                unit,
                boq_style
            )

        ])

    boq_table = Table(

        boq_data,

        repeatRows=1,

        colWidths=[

            18 * mm,   # Item No

            120 * mm,  # Description

            20 * mm,   # Qty

            22 * mm    # Unit

        ]

    )

    boq_table.setStyle(

        TableStyle([

            (
                "GRID",
                (0, 0),
                (-1, -1),
                0.5,
                colors.black
            ),

            (
                "BACKGROUND",
                (0, 0),
                (-1, 0),
                colors.HexColor("#E9ECEF")
            ),

            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "TOP"
            )

        ])

    )

    story.append(
        boq_table
    )

    doc.build(
        story,
        onFirstPage=add_page_elements,
        onLaterPages=add_page_elements
    )

    pdf = buffer.getvalue()

    buffer.close()

    return pdf
